baseURL: "https://davidbarrell.me/"
title: "David Barrell"
enableGitInfo: true
# googleAnalytics: ""

permalinks:
    posts: /:year/:month/:title/

menu:
    main:
    - identifier: about
      name: about
      url: /
      weight: 1
    - name: projects
      url: /projects
      weight: 2
    # - name: posts
    #   url: /posts
    #   weight: 3
    - name: engineering resume
      url: /engineering
      weight: 4
    - name: creative resume
      url: /creative
      weight: 5
